### PR TITLE
kkv-2 sidecar compability

### PR DESCRIPTION
**Pull request by NiklasJonsson6**
this allows kkv to run as a sidecar without configuring rbac for a watch we will not use, and without ugly-setting envs we dont care about

### CODE REVIEW

**Review by atamon — APPROVED** [review]
This makes sense, but do we have a way to detect (and possibly reject) if a target is expecting updates from a kkv that is not enabled for it?

Maybe this is where the get/keys/values header that we talked about for validating consistency between consumers and targets comes in? But I don't feel like we have to scope that into this PR

**Review by solsson — CHANGES_REQUESTED** [review]
The diff was a bit confusing, but it does a good job at removing unused config references so that's a 👍 

To yaml authors: When there's no env `TARGET_SERVICE_NAME` (or empty env value) KKV doesn't need RBAC and ~~assumes that onupdate target is localhost:$TARGET_SERVICE_PORT~~.

Nope, now that I think of it there can be two different configurations:
- Disable onupdate behavior completely. This also voids the need for RBAC.
- Disable service/DNS based onupdate, for sidecars that should do onupdate. This also voids the need for RBAC. In this mode we use localhost or 127.0.0.1 (whatever we used before the kkv2 transition).

**Comment by NiklasJonsson6** [comment]
Blocked by (this PR also needs to fix) https://github.com/Yolean/kafka-keyvalue/issues/44

**Comment by NiklasJonsson6** [comment]
After the last few commits:
- https://github.com/Yolean/kafka-keyvalue/issues/44 is fixed.
  - And improved! We now determine the stage based on all topic-partitions, not simply the first one that would trigger a stage change (which caused early readiness for topics with more than a single partition).
- The old unused "hc" webclient code is removed.
- The structure of ConsumerAtLeastOnce should (hopefully) be much more readable and testable. It resulted in:
  - Metrics are fixed. We had a bug where metrics that should report updates reported number of records consumed, and vice versa. 
  - We only produce metrics directly related to KKV (metrics only reporting information about the kafka topic is removed, ask kafka for metrics about that!).
  - The startup behavior (not sending updates when polling historical, etc.) is now tested properly. This should aleviate a lot of nervousness (which at least I had) about changing code in ConsumerAtLeastOnce.
- A QuarkusTest using devservices tests the entire application.
  - This is dependent on Docker when running tests. If we don't want this dependency, let's disable the test. It was massively useful during development and actually asserts the application behavior now.
- No more warnings or errors about annotations
  - The hacky health-proxies that tried to handle some strange old CDI bug are replaced with conventional health checks.
- Requesting current offset for a non-existing topic-partition no longer throws (returns null as per spec)

**Comment by solsson** [comment]
Is it reasonable that native builds with JDK 20 + Mandrel 23 are significantly larger than with JDK 17 + Mandrel 22.3?

Screenshot 2023-11-30 at 13 46 11

**Comment by solsson** [comment]
Regarding https://github.com/Yolean/kafka-keyvalue/pull/53/commits/647a089d8c97c1f14c99dd9ad2f83fb65a86045c it might have been some cache in buildkit that was the culprit, but from the Skaffold output it sure looks like it only checks if the tag exists or not, regardless of the current value of --platform.

image

**Comment by NiklasJonsson6** [comment]
> [IDEs will now run the integration tests, and so does test.sh](https://github.com/Yolean/kafka-keyvalue/pull/53/commits/6225f31ec79c67a8c75faa288f6485bb8415317d)

Cool!

**Pull request merged**
