### PR TITLE
De-support topics emptied by retention, to fix unwanted readiness

### PR DESCRIPTION
**Pull request by solsson**
Merging this deliberately reopens #44 because we have no such use cases anymore and the solution appears flawed (as both code comments and commit comments hinted)

### CODE REVIEW

**Comment by solsson** [comment]
`yolean/kafka-keyvalue:30fdd0b5416cf0a9a4357902f46804071e270941@sha256:908f49156f99e55d1d1f06eb76ecda37bc3fda36e7d4854bd391de99361aea8d`

**Comment by solsson** [comment]
Now running on dev3

**Review by atamon — APPROVED** [review]

**Comment by solsson** [comment]
I've failed to confirm that `kkv_cache_keys` gauge is exported in production. In unit tests it's reported as NaN. There might be something I haven't understood about Micrometer gauges.

**Comment by solsson** [comment]
`0b2400cd0baa21242401ed9ea7bc5ee14bc209e1@sha256:36a073f391fd1323fe2541fd3a4bcc9709cc9486f1912ffeb4f3711fe675f2af`

**Pull request merged**
